### ISSUE TITLE
Update font to Segoe UI

### ISSUE THREAD

**Issue by BlackPhlox** [joachimdalen/azdevops-work-item-wiki#10]
Update parsed markdown from `font-family: sans-serif` to Segoe UI to match Wiki's font with the appropriate fallback fonts.

**Comment by joachimdalen** [comment]
Hey! I'll look into this :)

**Comment by joachimdalen** [comment]
I fixed the issue causing the override of the default font. Will be testing this with the other changes and releasing the updates over the weekend.

**Comment by joachimdalen** [comment]
Released this in `v1.3.0`.
