### ISSUE TITLE
Images is always read from `wikiMaster`

### ISSUE THREAD

**Issue by BlackPhlox** [joachimdalen/azdevops-work-item-wiki#11]
When parsing images, the reference is asuming the wiki is from the master branch: `versionDescriptor.version=wikiMaster`.
I don't think there is a way to get from which branch the wiki is from directly via the url i.e.:
`https://dev.azure.com/orgname/ProjectName/_wiki/wikis/WikiName/1/Wiki-Page`

One way to fix this would be to add an option setting field allowing you to specify the branch and use it as input like so:
Branch name: `test123`

`https://orgname.visualstudio.com/d34a4258-7594-4db8-bbcb-361795a73a8d/_apis/git/repositories/625dc43b-e19f-4276-8316-41dc328b56f6/Items?path=/.attachments/test_img.png&download=false&resolveLfs=true&%24format=octetStream&api-version=5.0-preview.1&sanitize=true&versionDescriptor.version=test123`

**Comment by joachimdalen** [comment]
Yes, there are a few things in this extension that could be improved, it was made quick because it was needed and I kinda forgot about this. I'll add a custom field to the control allowing you to specify the branch to load from.

**Comment by joachimdalen** [comment]
I added the optional parameter that can be used when publishing a wiki from a different branch than `wikiMaster`. This change will also improve better handling for attachments and images that rendered with the wrong path in the url. Will be testing this with the other changes and releasing the updates over the weekend.
