### ISSUE TITLE
Links should be parsed as `target="_blank"`

### ISSUE THREAD

**Issue by BlackPhlox** [joachimdalen/azdevops-work-item-wiki#12]
When rendering a markdown link i.e. `[Text](www.link.com)`
```html
<a href="www.link.com">Text</a>
```
Does not include `target="_blank"` meaning it opens inside the rendered frame. Allowing to do fun stuff like recursion etc. `target="_blank"` Should be the default behavior when parsed.

**Comment by joachimdalen** [comment]
You are correct, I'll look into updating this in the parser :)

**Comment by joachimdalen** [comment]
I updated the renderer for all links to add the same attributes as Azure DevOps does. Will be testing this with the other changes and releasing the updates over the weekend.

**Comment by joachimdalen** [comment]
Released this in `v1.3.0`.
